# Generated by Django 6.0.6 on 2026-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registration_unique_event_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='facility_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
