# Generated by Django 6.0.6 on 2026-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
