# Generated by Django 6.0.6 on 2026-07-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventtype_event_free_or_paid_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='icon',
            field=models.CharField(default='event', help_text='Material Symbols icon name', max_length=50, null=True),
        ),
    ]
