# Generated by Django 6.0.6 on 2026-07-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventtype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='free_or_paid',
            new_name='registration_type',
        ),
        migrations.AddField(
            model_name='event',
            name='registration_closes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
