# Generated by Django 6.0.6 on 2026-07-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_free_or_paid_event_registration_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='checked_in_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_checked_in',
        ),
        migrations.AddField(
            model_name='event',
            name='attendance_mode',
            field=models.CharField(choices=[('single', 'Single Check-in'), ('daily', 'Daily Check-in')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='checkin_mode',
            field=models.CharField(choices=[('staff_only', 'Staff Only'), ('self_only', 'Self Check-In Only'), ('both', 'Staff + Self Check-In')], default='staff_only', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='events.registration')),
            ],
        ),
        migrations.CreateModel(
            name='EnabledPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, help_text='Instructions for using this payment method for the event.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_payment_methods', to='events.event')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_payment_methods', to='events.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response', models.TextField(blank=True)),
                ('event_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='events.enabledpaymentmethod')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.registration')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Total number of tickets available.')),
                ('sold', models.PositiveIntegerField(default=0, help_text='Total number of tickets sold.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the ticket type is active or not.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.tickettype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('registration', 'attendance_date'), name='unique_daily_checkin'),
        ),
        migrations.AddConstraint(
            model_name='enabledpaymentmethod',
            constraint=models.UniqueConstraint(fields=('event', 'payment_method'), name='unique_event_payment_method'),
        ),
    ]
